export const mockEpisodeData = [
    {
        provider: "Erai -raws",
        episodes: [
            // ... previous episodes
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 28,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "290 MB",
                date: "2023-09-29",
                seedCount: 70,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 20,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "300 MB",
                date: "2023-10-06",
                seedCount: 85,
                leechCount: 9,
                downloads: 1500,
            },
        ]
    },
    {
        provider: "Anime Time",
        episodes: [
            // ... previous episodes
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
            {
                episodeNumber: 33,
                episodeTitle: "Episode 33 Title",
                commentsCount: 30,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode33.torrent",
                },
                size: "290 MB",
                date: "2023-09-15",
                seedCount: 80,
                leechCount: 14,
                downloads: 1400,
            },
            {
                episodeNumber: 34,
                episodeTitle: "Episode 34 Title",
                commentsCount: 25,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode34.torrent",
                },
                size: "270 MB",
                date: "2023-09-22",
                seedCount: 70,
                leechCount: 10,
                downloads: 1100,
            },
        ]
    },
    {
        provider: "SubsPlease",
        episodes: [
            // ... previous episodes
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
            {
                episodeNumber: 37,
                episodeTitle: "Episode 37 Title",
                commentsCount: 26,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode37.torrent",
                },
                size: "280 MB",
                date: "2023-10-13",
                seedCount: 75,
                leechCount: 12,
                downloads: 1200,
            },
            {
                episodeNumber: 38,
                episodeTitle: "Episode 38 Title",
                commentsCount: 19,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode38.torrent",
                },
                size: "290 MB",
                date: "2023-10-20",
                seedCount: 85,
                leechCount: 11,
                downloads: 1300,
            },
        ]
    },
    {
        provider: "ToonsHub",
        episodes: [
            // ... previous episodes
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 35,
                episodeTitle: "Episode 35 Title",
                commentsCount: 22,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode35.torrent",
                },
                size: "260 MB",
                date: "2023-09-29",
                seedCount: 65,
                leechCount: 8,
                downloads: 1000,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
            {
                episodeNumber: 36,
                episodeTitle: "Episode 36 Title",
                commentsCount: 18,
                links: {
                    magnetLink: "magnet:?...",
                    downloadLink: "https://example.com/episode36.torrent",
                },
                size: "270 MB",
                date: "2023-10-06",
                seedCount: 75,
                leechCount: 9,
                downloads: 1100,
            },
        ]
    },
    // ... add more providers and episodes
];

